version: "3.4"

services:
  keycloak_db:
    image: postgres:15-alpine
    environment:
        - POSTGRES_DB=${POSTGRES_DATABASE}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    networks:
      parser_network:
    volumes:
      - ./data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    hostname: keycloak
    ports:
      - "8443:8443"  # Используем порт 8443 для HTTPS
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=${POSTGRES_DATABASE}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_SCHEMA=public
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      parser_network:
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
    volumes:
      - ./server.crt:/etc/x509/https/tls.crt  # Путь к вашему SSL-сертификату
      - ./server.key:/etc/x509/https/tls.key  # Путь к вашему SSL-ключу

networks:
  parser_network:
    driver: bridge
